/* Generated by PScript */
var _pymeth_replace = function (s1, s2, count) {  // nargs: 2 3
    if (this.constructor !== String) return this.replace.apply(this, arguments);
    var i = 0, i2, parts = [];
    count = (count === undefined) ? 1e20 : count;
    while (count > 0) {
        i2 = this.indexOf(s1, i);
        if (i2 >= 0) {
            parts.push(this.slice(i, i2));
            parts.push(s2);
            i = i2 + s1.length;
            count -= 1;
        } else break;
    }
    parts.push(this.slice(i));
    return parts.join('');
};
var hl, nhl;
nhl = document.getElementById("tohighlight").textContent;
hl = _pymeth_replace.call(nhl, "/", "<symbolify>/</symbolify>");
document.getElementById("tohighligt").innerHTML = hl;
